### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by federico22285** [dtrizna/dotNETinject#2]
hackme@Hacking:~/Downloads$ python3 xxx.py hackme.exe x64
[!] Generating x64 shellcode from file:
    hackme.exe
Segmentation fault

**Comment by dtrizna** [comment]
This problem was present in specific versions of donut: https://github.com/TheWover/donut/issues/29

But yes - no code updates from my side. Taking into account sensitivity of this research, code if provided as Proof of Concept.

If you want to use such malware for ethical purposes, you need to understand, how to fix this if your environments requires additional tunage.
